[package]
name = "influxdb_iox"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"
default-run = "influxdb_iox"

[workspace]
members = [
    "arrow_deps",
    "server",
    "data_types",
    "generated_types",
    "ingest",
    "influxdb_line_protocol",
    "object_store",
    "mem_qe",
    "segment_store",
    "packers",
    "test_helpers",
    "influxdb_tsm",
    "query",
    "wal",
    "write_buffer",
    "influxdb2_client",
]

[profile.release]
debug = true

[dependencies]
data_types = { path = "data_types" }
arrow_deps = { path = "arrow_deps" }
generated_types = { path = "generated_types" }
ingest = { path = "ingest" }
influxdb_line_protocol = { path = "influxdb_line_protocol" }
mem_qe = { path = "mem_qe" }
segment_store = { path = "segment_store" }
packers = { path = "packers" }
write_buffer = { path = "write_buffer" }
object_store = { path = "object_store" }
query = { path = "query" }
influxdb_tsm = { path = "influxdb_tsm" }
wal = { path = "wal" }

bytes = "0.5.4"
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }

clap = "2.33.1"
dotenv = "0.15.0"
dirs = "3.0.1"
env_logger = "0.7.1"
futures = "0.3.1"

serde_json = "1.0.44"
serde_urlencoded = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
byteorder = "1.3.4"

tonic = "0.3.1"
prost = "0.6.1"
prost-types = "0.6.1"
tracing = "0.1"
tracing-futures="0.2.4"

http = "0.2.0"
snafu = "0.6.9"
libflate = "1.0.0"

[dev-dependencies]
assert_cmd = "1.0.0"
criterion = "0.3"
test_helpers = { path = "test_helpers" }
hex = "0.4.2"
influxdb2_client = { path = "influxdb2_client" }
libflate = "1.0.0"
rand = "0.7.2"
reqwest = "0.10.1"
predicates = "1.0.4"
tempfile = "3.1.0"


[[bin]]
name = "cpu_feature_check"
path = "src/cpu_feature_check/main.rs"


[[bench]]
name = "encoders"
harness = false

[[bench]]
name = "line_parser"
harness = false

[[bench]]
name = "mapper"
harness = false

[[bench]]
name = "line_protocol_to_parquet"
harness = false

[[bench]]
name = "packers"
harness = false
