[package]
name = "write_buffer"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"

[dependencies]

arrow_deps = { path = "../arrow_deps" }
data_types = { path = "../data_types" }
generated_types = { path = "../generated_types" }
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
query = { path = "../query" }
wal = { path = "../wal" }
test_helpers = { path = "../test_helpers" }

async-trait = "0.1"
chrono = "0.4"
flatbuffers = "0.6.1"
snafu = "0.6.2"
sqlparser = "0.6.1"
string-interner = "0.12.0"
tokio = { version = "0.2", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
test_helpers = { path = "../test_helpers" }
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
