[package]
name = "arrow_deps"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"
description = "Apache Arrow / Parquet / DataFusion dependencies for InfluxDB IOx, to ensure consistent versions and unified updates"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# We are using development version of arrow/parquet/datafusion and the dependencies are at the same rev

# The version can be found here: https://github.com/apache/arrow/commit/ceb9471be3d4500cefceaf673f2266a37e845331
#
arrow = { git = "https://github.com/apache/arrow.git", rev = "ceb9471be3d4500cefceaf673f2266a37e845331" , features = ["simd"] }
datafusion = { git = "https://github.com/apache/arrow.git", rev = "ceb9471be3d4500cefceaf673f2266a37e845331" }
# Turn off the "arrow" feature; it currently has a bug that causes the crate to rebuild every time
# and we're not currently using it anyway
parquet = { git = "https://github.com/apache/arrow.git", rev = "ceb9471be3d4500cefceaf673f2266a37e845331", default-features = false, features = ["snap", "brotli", "flate2", "lz4", "zstd"] }
